url: http://blog.penso.info
markdown: kramdown
base_url: /
relative_permalinks: false
title: Fabien Penso
description: "Fabien Penso's blog"
exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "sass_converter.rb", "Gemfile", "Gemfile.lock", ".tm_properties", "config.rb", "sass", "CNAME", "Procfile", "Vagrantfile", "s3_website.yml", "Guardfile"]
highlighter: pygments
permalink: /:year/:month/:day/:title/
toplinks: ['about', 'archive', 'contact', 'hire']
