# User Settings | Edit there as per required

title: Steven Watson Buehler
url: "http://swbuehler.github.io"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    Steven Watson Buehler<span class="faded">'s blog</span>

email: stevenwatsonbuehler@icloud.com
author: Steven Watson Buehler
# This description will show up in google search results
# (for index page) etc.
description: >
    Steven Bueher is a late-40-something autistic guy living on his own in Tampa Bay, Florida. Plays with games and data. 

# This will what will show against &copy; in the footer
copyright: Steven Watson Buehler
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    I'm a late-40-something guy with autism living on my own in Tampa Bay, Florida. This is my blog about gaming, dataplay, and life.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Steven is a late-40-something autistic guy living in Tampa Bay, Florida.

about_footer: true

twitter_username: doombuggygames
github_username: swbuehler
facebook_id: stevenwatsonbuehler

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-101506026-3 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "https://pbs.twimg.com/profile_images/1128735737459957760/t2WrQ0nY_400x400.png" # This will show in facebook thumbnails
twitter_image: "https://pbs.twimg.com/profile_images/1128735737459957760/t2WrQ0nY_400x400.png" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
