url: http://www.stevenwatsonbuehler.com
markdown: kramdown
base_url: /
relative_permalinks: false
title: Steven Watson Buehler
description: "Steven Watson Buehler's blog"
exclude: [".rvmrc", ".rbenv-version", "README", "Rakefile", "changelog.md", "sass_converter.rb", "Gemfile", "Gemfile.lock", ".tm_properties", "config.rb", "sass", "CNAME", "Procfile", "Vagrantfile", "s3_website.yml", "Guardfile"]
highlighter: 'rouge'
permalink: /:year/:month/:day/:title/
toplinks: ['about', 'archive', 'contact', 'colophon']
